"""Initial migration.

Revision ID: 37821079971f
Revises: 4010d75cef28
Create Date: 2024-08-12 09:22:45.841884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37821079971f'
down_revision = '4010d75cef28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
