"""Update Task model with owner relationship

Revision ID: 4010d75cef28
Revises: bb332ab521bf
Create Date: 2024-08-12 04:13:43.232674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4010d75cef28'
down_revision = 'bb332ab521bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('can_view_status')

    # ### end Alembic commands ###
